### ISSUE TITLE
npm install fails

### ISSUE THREAD

**Issue by aioue** [azu/opml-to-markdown#1]
ubuntu 14.04

![image](https://cloud.githubusercontent.com/assets/1254905/7094560/49d246f4-dfba-11e4-8c75-9d956fc9bd22.png)

**Comment by azu** [comment]
> Error: failed to fetch from registry

It seems to be issue with npm registory or network issue.
Please retry to `npm info opml-to-markdown -g`.

**Comment by aioue** [comment]
![image](https://cloud.githubusercontent.com/assets/1254905/7446668/633a7a32-f1d8-11e4-8fb5-73b5f33cfcdb.png)

**Comment by aioue** [comment]
Closing. Module abandoned.
